const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const API_BASE = 'https://kavantq-real-market-api-production.up.railway.app';
let state={symbol:'SPY',tf:'1Min',bars:[],provider:null,feed:null,market:null,connected:false,engine:false,mode:'candles',eq:100000,pos:null,poll:null,visible:55,offset:0,lastError:null};
const audit=[]; const ptr=new Map(); let dragStart=null,pinchStart=null;
const gateDefs={
 'DATA SENTINEL':{meaning:'Verifies the price feed is authentic, identified, fresh, ordered, and timestamped before KAVANTQ trusts it.',action:'Restore the authorized market-data connection, then confirm the newest provider timestamp is within the expected session interval.',effect:'HOLD blocks new paper orders because stale or unidentified prices make every downstream calculation unsafe.'},
 'VET':{meaning:'Validates the instrument, bar structure, timestamp sequence, and minimum evidence needed before analysis.',action:'Load enough valid bars for the selected timeframe and clear symbol/time ordering errors.',effect:'HOLD prevents strategy evaluation; PASS means the dataset is structurally usable, not that a trade is good.'},
 'SKEPTIC':{meaning:'Challenges a trade thesis and looks for contradictory evidence before execution.',action:'Submit a defined thesis/signal plus invalidation evidence. No thesis means no automatic PASS.',effect:'WATCH/HOLD means the system has not falsified or confirmed a trade thesis yet.'},
 'FAIR VALUE':{meaning:'Compares market price with an independently justified value or model range.',action:'Connect a research/fundamental model and record assumptions, model date, and confidence interval.',effect:'WATCH means KAVANTQ will not claim valuation edge from price movement alone.'},
 'LIQUIDITY':{meaning:'Checks whether expected order size can trade without unreasonable market impact.',action:'Use real quote/depth/volume data and compare intended size with current liquidity.',effect:'HOLD/WATCH constrains position sizing and can block thin instruments.'},
 'SPREAD':{meaning:'Measures bid/ask spread against policy limits before a paper/live order is considered.',action:'Connect a real quote feed and compare spread in basis points with the configured threshold.',effect:'HOLD/WATCH means transaction-cost uncertainty remains unresolved.'},
 'COST':{meaning:'Accounts for fees, commissions, exchange charges, financing and other explicit trading costs.',action:'Attach the venue/broker cost schedule for the instrument being evaluated.',effect:'WATCH means apparent edge has not yet been proven net of costs.'},
 'SLIPPAGE':{meaning:'Estimates the difference between intended price and realistically executable price.',action:'Use real spread/liquidity history and execution assumptions appropriate to order type and size.',effect:'WATCH reduces or rejects edge that disappears under realistic execution.'},
 'CATALYST':{meaning:'Identifies scheduled or live events that can invalidate ordinary price assumptions.',action:'Connect current event/news/calendar evidence and timestamp it.',effect:'WATCH means event risk is unknown; policy may reduce size or require manual review.'},
 'CORRELATION':{meaning:'Checks whether a new position duplicates exposure already present in the portfolio.',action:'Load current positions and recent cross-asset returns to calculate concentration/correlation.',effect:'WATCH/HOLD can cap size even when the individual trade looks acceptable.'},
 'RISK GOV.':{meaning:'Enforces non-negotiable capital, drawdown, exposure and kill-switch limits independently of strategy.',action:'Remain inside the risk constitution. Any breach requires flatten/hold and explicit human review.',effect:'PASS permits paper operation inside policy; it never overrides a failed upstream evidence gate.'}
};
function log(msg){audit.unshift(`${new Date().toLocaleTimeString()} · ${msg}`);$('#auditLog').innerHTML=audit.slice(0,120).map(x=>`<div>${escapeHtml(x)}</div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nyTime(iso){if(!iso)return '—'; return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',timeZoneName:'short'}).format(new Date(iso))}
function ageSec(iso){return iso?Math.max(0,(Date.now()-new Date(iso).getTime())/1000):Infinity}
function tfExpectedSec(){return ({'1Min':60,'5Min':300,'15Min':900,'1Hour':3600,'1Day':86400})[state.tf]||60}
function gateStatuses(){let newest=state.bars.at(-1),fresh=ageSec(newest?.t),expected=tfExpectedSec();let dataPass=state.connected&&Number.isFinite(fresh)&&(state.market?.is_open?fresh<=Math.max(90,expected*1.5):true);let enough=state.bars.length>=20&&state.bars.every((b,i,a)=>i===0||new Date(b.t)>=new Date(a[i-1].t));return {
 'DATA SENTINEL':dataPass?['PASS',`Verified ${state.feed||'feed'} bar; ${state.market?.is_open?Math.round(fresh)+'s old':'market closed / last verified bar retained'}`,`provider=${state.provider||'—'}\nfeed=${state.feed||'—'}\nlast_bar=${newest?.t||'—'}\nmarket_open=${!!state.market?.is_open}`]:['HOLD',state.lastError||'No verified real-market feed','No trustworthy provider bar is currently available.'],
 'VET':enough?['PASS',`${state.bars.length} ordered ${state.tf} bars loaded`,`symbol=${state.symbol}\ntimeframe=${state.tf}\nbars=${state.bars.length}`]:['HOLD','Insufficient/invalid bar history',`bars=${state.bars.length}`],
 'SKEPTIC':['WATCH','No active thesis has been submitted','No thesis / invalidation packet attached.'],
 'FAIR VALUE':['WATCH','Independent valuation model not connected','Price data alone is not fair-value evidence.'],
 'LIQUIDITY':state.connected?['WATCH','Trade-size liquidity model not yet evaluated',`last_volume=${newest?.v??'—'}`]:['HOLD','Quote/volume feed unavailable','No verified liquidity evidence.'],
 'SPREAD':['WATCH','Bid/ask quote validation not connected','Bar data cannot prove current spread.'],
 'COST':['WATCH','Broker/venue cost schedule not attached','Explicit cost evidence pending.'],
 'SLIPPAGE':['WATCH','Execution-impact model not evaluated','Slippage evidence pending.'],
 'CATALYST':['WATCH','Current catalyst/calendar feed not connected','Event-risk evidence pending.'],
 'CORRELATION':state.pos?['WATCH','Portfolio correlation model pending',`open_position=${state.pos.sym} ${state.pos.side}`]:['WATCH','No portfolio correlation calculation yet','No open paper position.'],
 'RISK GOV.':['PASS','Paper-only mode; real-money routing disabled','capital_mode=PAPER\nreal_money_routing=false\nkill_switch=armed']};}
function renderGates(){const s=gateStatuses();$('#gates').innerHTML=Object.entries(s).map(([name,[st,why]])=>`<button class="gate" data-gate="${name}"><span class="name">${name}</span><span class="state ${st==='PASS'?'green':st==='WATCH'?'amber':'red'}">${st}</span><span class="reason">${escapeHtml(why)}</span></button>`).join(''); $$('.gate').forEach(b=>b.addEventListener('click',()=>openGate(b.dataset.gate)))}
function openGate(name){const [st,why,evidence]=gateStatuses()[name]; const d=gateDefs[name]; $('#gateTitle').textContent=name;$('#gateState').textContent=st;$('#gateState').className=st==='PASS'?'green':st==='WATCH'?'amber':'red';$('#gateMeaning').textContent=d.meaning;$('#gateWhy').textContent=why;$('#gateEvidence').textContent=evidence;$('#gateAction').textContent=d.action;$('#gateEffect').textContent=d.effect;$('#gateDialog').showModal()}
async function loadBars(){clearTimeout(state.poll);try{const u=new URL(`${API_BASE}/market`);u.searchParams.set('symbol',state.symbol);u.searchParams.set('timeframe',state.tf);u.searchParams.set('limit','350');const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||`feed ${r.status}`);state.bars=(j.bars||[]).sort((a,b)=>new Date(a.t)-new Date(b.t));state.provider=j.provider;state.feed=j.feed;state.market=j.market;state.connected=state.bars.length>0;state.lastError=null;state.offset=0;$('#feedStatus').textContent=state.connected?'REAL FEED CONNECTED':'REAL FEED EMPTY';$('#feedStatus').className='status-pill '+(state.connected?'pass':'hold');$('#provider').textContent=`Provider: ${j.provider||'—'} / ${j.feed||'—'}`;$('#marketClock').textContent=`Market: ${j.market?.is_open?'OPEN':'CLOSED'} · ${nyTime(j.market?.timestamp)}`;renderQuote();draw();renderGates();}catch(e){state.connected=false;state.lastError=e.message;$('#feedStatus').textContent='REAL FEED OFFLINE';$('#feedStatus').className='status-pill hold';$('#provider').textContent='Provider: secure backend not connected';$('#marketClock').textContent='Market: unavailable';$('#barClock').textContent='Last bar: unavailable';$('#freshness').textContent='Freshness: unavailable';renderGates();draw();log(`Feed HOLD: ${e.message}`)}finally{state.poll=setTimeout(loadBars,state.engine?5000:15000)}}
function renderQuote(){const b=state.bars.at(-1);if(!b){$('#last').textContent='$—';$('#ohlc').textContent='O — H — L — C — V —';return}$('#ticker').textContent=state.symbol;$('#last').textContent='$'+Number(b.c).toFixed(2);$('#ohlc').textContent=`O ${b.o.toFixed(2)} H ${b.h.toFixed(2)} L ${b.l.toFixed(2)} C ${b.c.toFixed(2)} V ${Number(b.v).toLocaleString()}`;$('#barClock').textContent='Last bar: '+nyTime(b.t);const a=ageSec(b.t);$('#freshness').textContent=`Freshness: ${Math.round(a)}s`;let pnl=state.pos?(b.c-state.pos.entry)*state.pos.qty*(state.pos.side==='BUY'?1:-1):0;$('#pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('#pnl').className=pnl>=0?'green':'red';$('#equity').textContent='$'+(state.eq+pnl).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});$('#exposure').textContent=(state.pos?state.pos.value/state.eq*100:0).toFixed(2)+'%';$('#positionsList').innerHTML=state.pos?`<div class="position"><b>${state.pos.sym}</b> · ${state.pos.side} · ${state.pos.qty.toFixed(3)} shares · entry $${state.pos.entry.toFixed(2)} · mark $${b.c.toFixed(2)} · <span class="${pnl>=0?'green':'red'}">${pnl>=0?'+':''}$${pnl.toFixed(2)}</span></div>`:'No positions.'}
function visibleBars(){if(!state.bars.length)return[];const n=Math.min(state.visible,state.bars.length);const end=Math.max(n,state.bars.length-state.offset);return state.bars.slice(Math.max(0,end-n),end)}
function draw(){const c=$('#chart'),wrap=$('#chartWrap'),d=devicePixelRatio||1,w=Math.max(1,wrap.clientWidth),h=Math.max(1,wrap.clientHeight);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const bars=visibleBars();if(!bars.length){x.fillStyle='#888';x.font='16px system-ui';x.textAlign='center';x.fillText('Real market data unavailable — synthetic candles disabled',w/2,h/2);return}const vals=bars.flatMap(b=>[b.h,b.l]),mn=Math.min(...vals),mx=Math.max(...vals),padL=10,padR=64,padY=24,plotW=w-padL-padR,plotH=h-padY*2,yy=v=>padY+(mx-v)/(mx-mn||1)*plotH,cw=plotW/bars.length;x.strokeStyle='#171717';x.fillStyle='#777';x.font='11px system-ui';x.textAlign='left';for(let i=0;i<5;i++){let y=padY+i*plotH/4;x.beginPath();x.moveTo(padL,y);x.lineTo(w-padR,y);x.stroke();let val=mx-(mx-mn)*i/4;x.fillText(val.toFixed(2),w-padR+7,y+4)}if(state.mode==='line'){x.strokeStyle='#ddb519';x.lineWidth=2;x.beginPath();bars.forEach((b,i)=>{let X=padL+i*cw+cw/2,Y=yy(b.c);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke()}else bars.forEach((b,i)=>{let X=padL+i*cw+cw/2,up=b.c>=b.o;x.strokeStyle=up?'#45df9a':'#ff6e79';x.fillStyle=x.strokeStyle;x.beginPath();x.moveTo(X,yy(b.h));x.lineTo(X,yy(b.l));x.stroke();let top=Math.min(yy(b.o),yy(b.c)),bh=Math.max(2,Math.abs(yy(b.o)-yy(b.c))),bw=Math.max(3,Math.min(12,cw*.62));x.fillRect(X-bw/2,top,bw,bh)})}
function zoom(delta){state.visible=Math.max(12,Math.min(220,state.visible+delta));draw()}
function pan(pxDelta){const bars=state.bars.length,perPx=state.visible/Math.max(200,$('#chartWrap').clientWidth),d=Math.round(pxDelta*perPx);state.offset=Math.max(0,Math.min(Math.max(0,bars-state.visible),state.offset+d));draw()}
function validPrice(){const b=state.bars.at(-1);return state.connected&&b&&Number.isFinite(b.c)?b.c:null}
function trade(side){const p=validPrice();if(p==null){log('ORDER BLOCKED: no verified real price');$('#tradeNote').textContent='ORDER BLOCKED — a verified real-market price is required.';return}let v=+$('#dollars').value||1000;if(v<=0)return;if(side==='CLOSE'&&state.pos){let pnl=(p-state.pos.entry)*state.pos.qty*(state.pos.side==='BUY'?1:-1);state.eq+=pnl;log(`CLOSE PAPER ${state.pos.sym} @ real mark ${p.toFixed(2)} P&L ${pnl.toFixed(2)}`);state.pos=null}else if(side==='SELL'&&!state.pos){state.pos={sym:state.symbol,side:'SELL',value:v,entry:p,qty:v/p,stop:+$('#stop').value||null,target:+$('#target').value||null};log(`SELL PAPER ${state.symbol} $${v.toFixed(2)} @ real mark ${p.toFixed(2)}`)}else if(side==='BUY'){state.pos={sym:state.symbol,side:'BUY',value:v,entry:p,qty:v/p,stop:+$('#stop').value||null,target:+$('#target').value||null};log(`BUY PAPER ${state.symbol} $${v.toFixed(2)} @ real mark ${p.toFixed(2)}`)}renderQuote();renderGates()}
$('#gateClose').onclick=()=>$('#gateDialog').close();$('#gateDialog').addEventListener('click',e=>{if(e.target===$('#gateDialog'))$('#gateDialog').close()});
$('#symbol').onchange=()=>{state.symbol=$('#symbol').value;state.bars=[];state.offset=0;loadBars();log('Symbol '+state.symbol)};$$('.tf').forEach(b=>b.onclick=()=>{$$('.tf').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.tf=b.dataset.tf;state.bars=[];state.offset=0;loadBars();log('Timeframe '+b.textContent+' (provider aggregation)')});
$('#chartMode').onclick=()=>{state.mode=state.mode==='candles'?'line':'candles';$('#chartMode').textContent=state.mode.toUpperCase();draw()};$('#zoomIn').onclick=()=>zoom(-10);$('#zoomOut').onclick=()=>zoom(10);$('#resetView').onclick=()=>{state.visible=55;state.offset=0;draw()};
$('#engine').onclick=()=>{state.engine=!state.engine;$('#engine').textContent=state.engine?'PAUSE REAL-FEED SHADOW ENGINE':'START REAL-FEED SHADOW ENGINE';log(state.engine?'Real-feed shadow engine started':'Shadow engine paused');clearTimeout(state.poll);loadBars()};$('#kill').onclick=()=>{state.engine=false;state.pos=null;$('#engine').textContent='START REAL-FEED SHADOW ENGINE';renderQuote();renderGates();log('KILL / FLATTEN executed on PAPER book')};$('#buy').onclick=()=>trade('BUY');$('#sell').onclick=()=>trade(state.pos?'CLOSE':'SELL');
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
const wrap=$('#chartWrap');wrap.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?8:-8)},{passive:false});wrap.addEventListener('pointerdown',e=>{wrap.setPointerCapture?.(e.pointerId);ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ptr.size===1)dragStart=e.clientX;if(ptr.size===2){const a=[...ptr.values()];pinchStart={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),visible:state.visible}}});wrap.addEventListener('pointermove',e=>{if(!ptr.has(e.pointerId))return;ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ptr.size===1&&dragStart!=null){let dx=dragStart-e.clientX;if(Math.abs(dx)>8){pan(dx);dragStart=e.clientX}}else if(ptr.size===2&&pinchStart){const a=[...ptr.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.visible=Math.max(12,Math.min(220,Math.round(pinchStart.visible*(pinchStart.dist/Math.max(20,dist)))));draw()}});['pointerup','pointercancel'].forEach(ev=>wrap.addEventListener(ev,e=>{ptr.delete(e.pointerId);if(ptr.size<2)pinchStart=null;if(ptr.size===0)dragStart=null}));window.addEventListener('resize',draw);
renderGates();draw();log('KAVANTQ v0.7 initialized — synthetic market generator removed');loadBars();