(()=>{'use strict';
const ROOT='/jericho-hour/';
const LANGS=[['en','English'],['fr','Français'],['es','Español'],['pt','Português'],['ar','العربية'],['ak','Twi / Akan'],['ee','Ewe'],['ga','Ga'],['ha','Hausa'],['yo','Yorùbá'],['ig','Igbo'],['sw','Kiswahili'],['am','Amharic'],['so','Somali'],['om','Afaan Oromo'],['ti','Tigrinya'],['rw','Kinyarwanda'],['ln','Lingála'],['wo','Wolof'],['zu','isiZulu'],['xh','isiXhosa'],['af','Afrikaans'],['sn','Shona'],['st','Sesotho'],['tn','Setswana']];
const WORDS={fr:{Home:'Accueil',Radio:'Radio',Sermons:'Sermons',Programs:'Programmes',Schedule:'Calendrier',Community:'Communauté',Feed:'Fil','Member sign in':'Espace membre','Give & support':'Donner'},es:{Home:'Inicio',Radio:'Radio',Sermons:'Sermones',Programs:'Programas',Schedule:'Calendario',Community:'Comunidad',Feed:'Actividad','Member sign in':'Miembros','Give & support':'Donar'},pt:{Home:'Início',Radio:'Rádio',Sermons:'Sermões',Programs:'Programas',Schedule:'Agenda',Community:'Comunidade',Feed:'Feed','Member sign in':'Membros','Give & support':'Doar'},ar:{Home:'الرئيسية',Radio:'الراديو',Sermons:'العظات',Programs:'البرامج',Schedule:'الجدول',Community:'المجتمع',Feed:'المنشورات','Member sign in':'دخول الأعضاء','Give & support':'العطاء'}};
const PLAYLIST=[
 {title:'Feel It',artist:'Matias Ruiz',lang:'Instrumental',kind:'Groovy Electronic Pop',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d3922e7457075e9015ac0/1717385517612/09+Matias+Ruiz+-+Feel+It.mp3/original/09+Matias+Ruiz+-+Feel+It.mp3'},
 {title:'BG Horizon',artist:'HOYLE',lang:'Instrumental',kind:'Hip Hop Chill',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d1ef03709161dc3668f16/1717378805158/HOYLE+-+BG+HORIZON.mp3/original/HOYLE+-+BG+HORIZON.mp3'},
 {title:'New Life',artist:'Frannie',lang:'English',kind:'Uplifting Worship Pop',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d3be4f5688e6d28766ba8/1717386218075/New+Life.mp3/original/New+Life.mp3'},
 {title:'Ancient Ones',artist:'Katie Overbeek',lang:'English',kind:'Reflective Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d45a2d100813e73e982a3/1717388714023/Ancient+Ones-MP3.mp3/original/Ancient+Ones-MP3.mp3'},
 {title:'It Is Finished (East to West)',artist:'Nai and J',lang:'English',kind:'Congregational Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665cf7c6db0ae912cb4c1baf/1717368794000/02+It+Is+Finished+%28East+To+West%29.mp3/original/02+It+Is+Finished+%28East+To+West%29.mp3'},
 {title:'By Your Side',artist:'Austin Sebek',lang:'Instrumental',kind:'Acoustic',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d3856f541c16df1136306/1717385389819/08+Austin+Sebek+-+By+Your+Side.mp3/original/08+Austin+Sebek+-+By+Your+Side.mp3'},
 {title:'Author Finisher',artist:'Katie Overbeek',lang:'English',kind:'Peaceful Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d448b3914ed5832197de4/1717388437218/Author+Finisher-MP3.mp3/original/Author+Finisher-MP3.mp3'},
 {title:'Fountains',artist:'Katie Overbeek',lang:'English',kind:'Acoustic Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d40ffe7457075e902c6ca/1717387529402/Fountains-MP3.mp3/original/Fountains-MP3.mp3'},
 {title:'For Good',artist:'Darla Baltazar',lang:'Instrumental',kind:'Ambient Chill',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d376be7457075e9010b24/1717385081427/07+Darla+Baltazar+-+For+Good.mp3/original/07+Darla+Baltazar+-+For+Good.mp3'},
 {title:'In A Moment',artist:'Worship Start contributor',lang:'English',kind:'Congregational Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d1910ac8d4a045abb1db8/1717377313254/05+In+A+Moment.mp3/original/05+In+A+Moment.mp3'},
 {title:'Isaías 41:10',artist:'BOUE',lang:'Spanish title / instrumental',kind:'Electronic Worship Instrumental',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d3ad06f594a43f7b50235/1717385948336/10+BOUE+-+Isai%CC%81as+41_10.mp3/original/10+BOUE+-+Isai%CC%81as+41_10.mp3'},
 {title:'I Will Say',artist:'Katie Overbeek',lang:'English',kind:'Hopeful Worship',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665d48d75be4466b3b92bbaa/1717389535116/I+Will+Say-MP3.mp3/original/I+Will+Say-MP3.mp3'},
 {title:'Lucid',artist:'The Seraphim Project',lang:'Instrumental',kind:'Ambient Rock',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665dcae4e6026821684d5e67/1717422832762/03+Lucid.mp3/original/03+Lucid.mp3'},
 {title:'Lunar',artist:'The Seraphim Project',lang:'Instrumental',kind:'Ambient Rock',src:'https://static1.squarespace.com/static/5e4b41568ae6b644169bed5a/t/665dce4443d6f53c87bf1357/1717423703586/07+Lunar.mp3/original/07+Lunar.mp3'}
]
const SOURCE='https://www.worshipstart.com/royaltyfreemusic';
const PREF='jh-pref-v13', PLAYER='jh-player-v13';
let pref={theme:'cream',lang:'en',dataMode:'low'};try{Object.assign(pref,JSON.parse(localStorage.getItem(PREF)||'{}'))}catch{}
let state={track:0,time:0,playing:false};try{Object.assign(state,JSON.parse(sessionStorage.getItem(PLAYER)||'{}'))}catch{}
let dock,playBtn,themeSel,langSel,trackLabel,audio,toast,saveTimer;
function persistPref(){try{localStorage.setItem(PREF,JSON.stringify(pref))}catch{}}
function persistPlayer(){if(!audio)return;state.time=Number.isFinite(audio.currentTime)?audio.currentTime:0;state.playing=!audio.paused;try{sessionStorage.setItem(PLAYER,JSON.stringify(state))}catch{}}
function flash(msg){if(!toast)return;toast.textContent=msg;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),3200)}
function sourceTrack(){return PLAYLIST[((state.track%PLAYLIST.length)+PLAYLIST.length)%PLAYLIST.length]}
function updateMeta(){const t=sourceTrack();if(trackLabel)trackLabel.innerHTML='<b>'+esc(t.title)+' · '+esc(t.artist)+'</b><small>'+esc(t.kind)+' · Worship Start royalty-free library · attribution required</small>';if(navigator.mediaSession){try{navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:'Jericho Hour demo playlist'})}catch{}}}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function loadTrack(autoplay=false,keepTime=false){if(!audio)return;const t=sourceTrack(),was=autoplay||!audio.paused;audio.src=t.src;audio.preload='metadata';audio.volume=.78;audio.addEventListener('loadedmetadata',()=>{if(keepTime&&state.time>0&&state.time<audio.duration-2){try{audio.currentTime=state.time}catch{}}},{once:true});updateMeta();if(was)audio.play().then(()=>{state.playing=true;playBtn.textContent='Ⅱ';persistPlayer()}).catch(()=>{state.playing=false;playBtn.textContent='▶';persistPlayer();flash('Tap Play to start audio. Your browser blocked automatic playback.')})}
function toggle(){if(audio.paused){audio.play().then(()=>{state.playing=true;playBtn.textContent='Ⅱ';persistPlayer()}).catch(()=>flash('Tap Play again after interacting with the page.'))}else{audio.pause();state.playing=false;playBtn.textContent='▶';persistPlayer()}}
function step(n){persistPlayer();state.track=(state.track+n+PLAYLIST.length)%PLAYLIST.length;state.time=0;loadTrack(true,false)}
function setTheme(v){pref.theme=v;document.documentElement.dataset.jhTheme=v;persistPref();if(themeSel)themeSel.value=v}
function translateNav(lang){pref.lang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';persistPref();const dict=WORDS[lang]||{};document.querySelectorAll('a,button').forEach(el=>{const raw=el.dataset.jhBase||(el.dataset.jhBase=el.textContent.trim());if(dict[raw])el.textContent=dict[raw]});if(langSel)langSel.value=lang}
function fullTranslate(){const lang=langSel?.value||'en';if(lang==='en'){flash('English is already selected.');return}const u='https://translate.google.com/translate?sl=en&tl='+encodeURIComponent(lang)+'&u='+encodeURIComponent(location.href);window.open(u,'_blank','noopener')}
function mountDock(){if(document.querySelector('.jh-radio-dock'))return;audio=new Audio();audio.playsInline=true;audio.addEventListener('ended',()=>step(1));audio.addEventListener('play',()=>{state.playing=true;if(playBtn)playBtn.textContent='Ⅱ';persistPlayer()});audio.addEventListener('pause',()=>{state.playing=false;if(playBtn)playBtn.textContent='▶';persistPlayer()});audio.addEventListener('timeupdate',()=>{if(!saveTimer){saveTimer=setTimeout(()=>{saveTimer=null;persistPlayer()},2000)}});audio.addEventListener('error',()=>flash('This track could not load. Try Next or open the music-rights library.'));
dock=document.createElement('aside');dock.className='jh-radio-dock';dock.setAttribute('aria-label','Jericho Hour persistent radio player');dock.innerHTML='<div class="jh-radio-inner"><div class="jh-radio-controls"><button class="jh-radio-skip" data-skip="-1" aria-label="Previous track">‹</button><button class="jh-radio-play" type="button" aria-label="Play radio">▶</button><button class="jh-radio-skip" data-skip="1" aria-label="Next track">›</button></div><div class="jh-radio-meta"></div><div class="jh-radio-actions"><span class="jh-live-state">DEMO RADIO</span><select aria-label="Site theme"><option value="cream">Cream</option><option value="burgundy">Reddish brown</option><option value="night">Black</option></select><select aria-label="Language"></select><button type="button" id="jhTranslate">Translate page</button><button type="button" id="jhPopout">↗ Player</button><a href="'+ROOT+'feed.html">Feed</a><a href="'+ROOT+'music-library.html">Music</a></div><div class="jh-radio-progress"><i></i></div></div>';
const ribbon=document.querySelector('.ribbon,.top,.stripe');if(ribbon)ribbon.insertAdjacentElement('afterend',dock);else document.body.prepend(dock);
playBtn=dock.querySelector('.jh-radio-play');trackLabel=dock.querySelector('.jh-radio-meta');themeSel=dock.querySelectorAll('select')[0];langSel=dock.querySelectorAll('select')[1];toast=document.createElement('div');toast.className='jh-radio-toast';document.body.append(toast);
LANGS.forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;langSel.append(o)});
themeSel.value=pref.theme;langSel.value=pref.lang;playBtn.onclick=toggle;dock.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>step(Number(b.dataset.skip)));dock.querySelector('#jhTranslate').onclick=fullTranslate;dock.querySelector('#jhPopout').onclick=()=>{const w=window.open(ROOT+'player.html','jhRadioPlayer','width=430,height=620,resizable=yes,scrollbars=yes');if(w)w.focus();else flash('Allow pop-ups to use the detached player.')};themeSel.onchange=()=>setTheme(themeSel.value);langSel.onchange=()=>{translateNav(langSel.value);flash('Navigation translated where built-in. Use “Translate page” for the full page.')};
if(navigator.mediaSession){navigator.mediaSession.setActionHandler?.('play',()=>audio.play());navigator.mediaSession.setActionHandler?.('pause',()=>audio.pause());navigator.mediaSession.setActionHandler?.('previoustrack',()=>step(-1));navigator.mediaSession.setActionHandler?.('nexttrack',()=>step(1))}
loadTrack(false,true);if(state.playing)setTimeout(()=>audio.play().then(()=>playBtn.textContent='Ⅱ').catch(()=>{state.playing=false;playBtn.textContent='▶'}),250);
window.addEventListener('beforeunload',persistPlayer)}
function hydrate(root=document){
 root.querySelector('#watch')?.addEventListener('click',()=>{const box=root.querySelector('#vid');if(!box)return;box.replaceChildren();const i=document.createElement('iframe');i.src='https://www.youtube-nocookie.com/embed/bGlp1kYrk68?autoplay=1';i.title='Jericho Hour Prayer Ministry published sermon';i.allow='autoplay; encrypted-media; picture-in-picture';i.allowFullscreen=true;box.append(i)});
 const tabs=[...root.querySelectorAll('[data-filter]')],posts=[...root.querySelectorAll('.post')],empty=root.querySelector('#empty');if(tabs.length&&posts.length){const apply=f=>{let n=0;posts.forEach(p=>{const show=f==='all'||p.dataset.kind===f;p.hidden=!show;if(show)n++});if(empty)empty.style.display=n?'none':'block';tabs.forEach(b=>b.setAttribute('aria-selected',String(b.dataset.filter===f)))};tabs.forEach(b=>b.onclick=()=>apply(b.dataset.filter));apply('all')}
 root.querySelector('#demoPost')?.addEventListener('click',()=>{const t=root.querySelector('#demoText'),s=root.querySelector('#composerState');if(!t||!s)return;if(!t.value.trim()){s.textContent='Write a sample first.';return}s.textContent='Preview only — nothing was published or saved.';t.value=''});
 renderCalendar(root);
}
function monthEvents(y,m){const ev={};const add=(d,t)=>{(ev[d]||(ev[d]=[])).push(t)};const days=new Date(y,m+1,0).getDate(),fr=[];for(let d=1;d<=days;d++){const dt=new Date(y,m,d),dow=dt.getDay();if(dow>=1&&dow<=5){add(d,'4:30–6:00 a.m. · Early Morning Prayer');add(d,'1:00–1:30 p.m. · Midday Prayer');add(d,'5:00–6:30 p.m. · Evening Prayer')}if(dow===0)add(d,'9:00–10:00 p.m. · Sunday Prayer');if(dow===5)fr.push(d)}if(fr.length){add(fr[0],'10:00–11:30 p.m. · First Friday Prayer');if(fr.at(-1)!==fr[0])add(fr.at(-1),'10:00–11:30 p.m. · Last Friday Prayer')}for(let d=Math.max(1,days-6);d<=days;d++){const dow=new Date(y,m,d).getDay();if(dow>=1&&dow<=5)add(d,'11:00 p.m.–midnight · Revival-week candidate (exact nights awaiting approval)')}return ev}
function renderCalendar(root=document){const host=root.querySelector('#calendar'),detail=root.querySelector('#calDetail');if(!host||host.dataset.ready)return;host.dataset.ready='1';let cur=new Date();function draw(){const y=cur.getFullYear(),m=cur.getMonth(),events=monthEvents(y,m),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();host.replaceChildren();const nav=document.createElement('div');nav.className='cal-nav';const prev=document.createElement('button'),next=document.createElement('button'),title=document.createElement('b');prev.textContent='‹';next.textContent='›';title.textContent=cur.toLocaleDateString(undefined,{month:'long',year:'numeric'});prev.onclick=()=>{cur=new Date(y,m-1,1);draw()};next.onclick=()=>{cur=new Date(y,m+1,1);draw()};nav.append(prev,title,next);host.append(nav);const grid=document.createElement('div');grid.className='cal-grid';['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>{const h=document.createElement('span');h.className='cal-head';h.textContent=x;grid.append(h)});for(let i=0;i<first;i++){const x=document.createElement('span');x.className='cal-empty';grid.append(x)}for(let d=1;d<=days;d++){const b=document.createElement('button');b.textContent=d;b.className=events[d]?'cal-day has-event':'cal-day';b.onclick=()=>{if(detail)detail.textContent=events[d]?.join(' • ')||'No recurring consultation-reported session on this date.'};grid.append(b)}host.append(grid)}draw()}
const SAFE=new Set(['','index.html','radio.html','sermons.html','programs.html','schedule.html','community.html','feed.html','resources.html','orphanage.html','music-library.html']);
async function softNav(url,push=true){try{const u=new URL(url,location.href),name=u.pathname.split('/').pop();if(!u.pathname.startsWith(ROOT)||!SAFE.has(name))return false;persistPlayer();const r=await fetch(u,{headers:{'X-JH-Partial':'1'}});if(!r.ok)return false;const txt=await r.text(),doc=new DOMParser().parseFromString(txt,'text/html'),main=doc.querySelector('main');if(!main)return false;document.querySelector('main')?.replaceWith(main);document.title=doc.title||document.title;if(push)history.pushState({jh:true},'',u.pathname+u.search+u.hash);document.querySelectorAll('.links a').forEach(a=>a.removeAttribute('aria-current'));const active=[...document.querySelectorAll('.links a')].find(a=>new URL(a.href,location.href).pathname===u.pathname);active?.setAttribute('aria-current','page');hydrate(document);window.scrollTo({top:0,behavior:'instant'});return true}catch{return false}}
function navIntercept(){document.addEventListener('click',async e=>{const a=e.target.closest('a');if(!a||e.defaultPrevented||a.target==='_blank'||a.hasAttribute('download')||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin||!u.pathname.startsWith(ROOT))return;const name=u.pathname.split('/').pop();if(!SAFE.has(name))return;e.preventDefault();if(!(await softNav(u,true)))location.href=u.href});window.addEventListener('popstate',()=>softNav(location.href,false))}
function augmentNav(){document.querySelectorAll('.links').forEach(nav=>{if(!nav.querySelector('a[href="feed.html"]')){const a=document.createElement('a');a.href='feed.html';a.textContent='Feed';const community=nav.querySelector('a[href="community.html"]');community?.insertAdjacentElement('afterend',a)||nav.append(a)}})}
function mount(){augmentNav();mountDock();setTheme(pref.theme);translateNav(pref.lang);hydrate(document);navIntercept()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();