(()=>{'use strict';
const ROOT='/jericho-hour/';
const LANGS=[['en','English'],['fr','Français'],['es','Español'],['pt','Português'],['ar','العربية'],['ak','Twi / Akan'],['ee','Ewe'],['ga','Ga'],['ha','Hausa'],['yo','Yorùbá'],['ig','Igbo'],['sw','Kiswahili'],['am','Amharic'],['so','Somali'],['om','Afaan Oromo'],['ti','Tigrinya'],['rw','Kinyarwanda'],['ln','Lingála'],['wo','Wolof'],['zu','isiZulu'],['xh','isiXhosa'],['af','Afrikaans'],['sn','Shona'],['st','Sesotho'],['tn','Setswana']];
const WORDS={fr:{Home:'Accueil',Radio:'Radio',Sermons:'Sermons',Programs:'Programmes',Schedule:'Calendrier',Community:'Communauté',Feed:'Fil','Member sign in':'Espace membre','Give & support':'Donner'},es:{Home:'Inicio',Radio:'Radio',Sermons:'Sermones',Programs:'Programas',Schedule:'Calendario',Community:'Comunidad',Feed:'Actividad','Member sign in':'Miembros','Give & support':'Donar'},pt:{Home:'Início',Radio:'Rádio',Sermons:'Sermões',Programs:'Programas',Schedule:'Agenda',Community:'Comunidade',Feed:'Feed','Member sign in':'Membros','Give & support':'Doar'},ar:{Home:'الرئيسية',Radio:'الراديو',Sermons:'العظات',Programs:'البرامج',Schedule:'الجدول',Community:'المجتمع',Feed:'المنشورات','Member sign in':'دخول الأعضاء','Give & support':'العطاء'}};
const PREF='jh-pref-v12';let pref={theme:'cream',lang:'en',dataMode:'low'};try{Object.assign(pref,JSON.parse(localStorage.getItem(PREF)||'{}'))}catch{}
let dock,playBtn,modeSel,themeSel,langSel,toast,ctx,nodes=[],timer=null,playing=false,startedAt=0,elapsed=0;
function persist(){try{localStorage.setItem(PREF,JSON.stringify(pref))}catch{}}
function flash(msg){if(!toast)return;toast.textContent=msg;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),3000)}
function stopSynth(){nodes.forEach(n=>{try{n.stop?.()}catch{};try{n.disconnect?.()}catch{}});nodes=[];clearInterval(timer);timer=null;if(ctx){ctx.close().catch(()=>{});ctx=null}if(playing)elapsed+=(performance.now()-startedAt)/1000;playing=false;try{sessionStorage.removeItem('jh-radio-playing')}catch{};if(playBtn)playBtn.textContent='▶'}
async function playSynth(){if(playing)return;try{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();playing=true;startedAt=performance.now();try{sessionStorage.setItem('jh-radio-playing','1')}catch{};playBtn.textContent='Ⅱ';const master=ctx.createGain();master.gain.value=.18;master.connect(ctx.destination);nodes.push(master);const progression=[[261.63,329.63,392],[196,246.94,392],[220,261.63,329.63],[174.61,220,261.63]];const schedule=()=>{if(!ctx||ctx.state==='closed')return;const now=ctx.currentTime,bar=Math.floor((elapsed+(performance.now()-startedAt)/1000)/4)%4;progression[bar].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===0?'triangle':'sine';o.frequency.value=f;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(i===0?.11:.07,now+.25);g.gain.setValueAtTime(i===0?.11:.07,now+3.4);g.gain.linearRampToValueAtTime(0,now+3.95);o.connect(g);g.connect(master);o.start(now);o.stop(now+4);nodes.push(o,g)});const bell=ctx.createOscillator(),bg=ctx.createGain();bell.type='sine';bell.frequency.value=[392,440,523.25,587.33][bar];bg.gain.setValueAtTime(0,now+.65);bg.gain.linearRampToValueAtTime(.05,now+.72);bg.gain.exponentialRampToValueAtTime(.001,now+1.65);bell.connect(bg);bg.connect(master);bell.start(now+.65);bell.stop(now+1.7);nodes.push(bell,bg)};schedule();timer=setInterval(schedule,4000);flash('Playing original demo bed. The real 24/7 stream is not commissioned yet.')}catch(e){stopSynth();flash('This browser blocked audio. Tap Play again after interacting with the page.') }}
function setTheme(v){pref.theme=v;document.documentElement.dataset.jhTheme=v;persist();if(themeSel)themeSel.value=v}
function translateNav(lang){pref.lang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';persist();const dict=WORDS[lang]||{};document.querySelectorAll('a,button').forEach(el=>{const raw=el.dataset.jhBase||(el.dataset.jhBase=el.textContent.trim());if(dict[raw])el.textContent=dict[raw]});if(lang!=='en'&&!WORDS[lang])flash('Language saved. Full-page translation will use the ministry self-hosted translation service when connected.');if(langSel)langSel.value=lang}
function mountDock(){if(document.querySelector('.jh-radio-dock'))return;dock=document.createElement('aside');dock.className='jh-radio-dock';dock.setAttribute('aria-label','Jericho Hour persistent radio player');dock.innerHTML=`<div class="jh-radio-inner"><button class="jh-radio-play" type="button" aria-label="Play radio demo">▶</button><div class="jh-radio-meta"><b>Jericho Hour Radio · persistent demo player</b><small>Original demo bed · navigation-safe preview · live station not commissioned</small></div><div class="jh-radio-actions"><span class="jh-live-state">DEMO</span><select aria-label="Future audio data mode"><option value="low">Low data · 32 kbps</option><option value="standard">Standard · 96 kbps</option></select><select aria-label="Site theme"><option value="cream">Cream</option><option value="burgundy">Reddish brown</option><option value="night">Black</option></select><select aria-label="Language"></select><a href="${ROOT}feed.html">Feed</a><a href="${ROOT}radio.html">Radio</a></div><div class="jh-radio-progress"><i></i></div></div>`;const ribbon=document.querySelector('.ribbon,.top');if(ribbon)ribbon.insertAdjacentElement('afterend',dock);else document.body.prepend(dock);playBtn=dock.querySelector('.jh-radio-play');const sels=dock.querySelectorAll('select');modeSel=sels[0];themeSel=sels[1];langSel=sels[2];toast=document.createElement('div');toast.className='jh-radio-toast';document.body.append(toast);LANGS.forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;langSel.append(o)});modeSel.value=pref.dataMode||'low';themeSel.value=pref.theme||'cream';langSel.value=pref.lang||'en';playBtn.onclick=()=>playing?stopSynth():playSynth();modeSel.onchange=()=>{pref.dataMode=modeSel.value;persist();flash(modeSel.value==='low'?'Future live stream: low-data 32 kbps mode selected. Demo audio is generated locally.':'Future live stream: standard 96 kbps mode selected. Demo audio is generated locally.')};themeSel.onchange=()=>setTheme(themeSel.value);langSel.onchange=()=>translateNav(langSel.value)}
function hydrate(root=document){
 root.querySelector('#watch')?.addEventListener('click',()=>{const box=root.querySelector('#vid');if(!box)return;box.replaceChildren();const i=document.createElement('iframe');i.src='https://www.youtube-nocookie.com/embed/bGlp1kYrk68?autoplay=1';i.title='Jericho Hour Prayer Ministry published sermon';i.allow='autoplay; encrypted-media; picture-in-picture';i.allowFullscreen=true;box.append(i)});
 const tabs=[...root.querySelectorAll('[data-filter]')],posts=[...root.querySelectorAll('.post')],empty=root.querySelector('#empty');if(tabs.length&&posts.length){const apply=f=>{let n=0;posts.forEach(p=>{const show=f==='all'||p.dataset.kind===f;p.hidden=!show;if(show)n++});if(empty)empty.style.display=n?'none':'block';tabs.forEach(b=>b.setAttribute('aria-selected',String(b.dataset.filter===f)))};tabs.forEach(b=>b.onclick=()=>apply(b.dataset.filter));apply('all')}
 root.querySelector('#demoPost')?.addEventListener('click',()=>{const t=root.querySelector('#demoText'),s=root.querySelector('#composerState');if(!t||!s)return;if(!t.value.trim()){s.textContent='Write a sample first.';return}s.textContent='Preview only — nothing was published or saved.';t.value=''});
}
const SAFE=new Set(['','index.html','radio.html','sermons.html','programs.html','community.html','feed.html','resources.html','orphanage.html']);
async function softNav(url,push=true){try{const u=new URL(url,location.href),name=u.pathname.split('/').pop();if(!u.pathname.startsWith(ROOT)||!SAFE.has(name))return false;const r=await fetch(u,{headers:{'X-JH-Partial':'1'}});if(!r.ok)return false;const text=await r.text(),doc=new DOMParser().parseFromString(text,'text/html'),main=doc.querySelector('main');if(!main)return false;document.querySelector('main')?.replaceWith(main);document.title=doc.title||document.title;if(push)history.pushState({jh:true},'',u.pathname+u.search+u.hash);document.querySelectorAll('.links a').forEach(a=>a.removeAttribute('aria-current'));const active=[...document.querySelectorAll('.links a')].find(a=>new URL(a.href,location.href).pathname===u.pathname);active?.setAttribute('aria-current','page');hydrate(document);window.scrollTo({top:0,behavior:'instant'});return true}catch{return false}}
function navIntercept(){document.addEventListener('click',async e=>{const a=e.target.closest('a');if(!a||e.defaultPrevented||a.target==='_blank'||a.hasAttribute('download')||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin||!u.pathname.startsWith(ROOT))return;const name=u.pathname.split('/').pop();if(!SAFE.has(name))return;e.preventDefault();if(!(await softNav(u,true)))location.href=u.href});window.addEventListener('popstate',()=>softNav(location.href,false))}
function mount(){mountDock();setTheme(pref.theme||'cream');translateNav(pref.lang||'en');hydrate(document);navIntercept();let resume=false;try{resume=sessionStorage.getItem('jh-radio-playing')==='1'}catch{};if(resume){setTimeout(()=>playSynth().catch?.(()=>{}),250)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();